export const url="https:// qashqadaryo.vatanparvar.uz/Files/News"
export const urlV="https://vatanparvar.uz/Files/News"
export const api="https:// qashqadaryo.vatanparvar.uz/"
export const urlFoto="https:// qashqadaryo.vatanparvar.uz/Files/Photogallery"
export const urlStat="https:// qashqadaryo.vatanparvar.uz/Files/StatisticElements"
export const urlPer="https:// qashqadaryo.vatanparvar.uz/Files/Personal"
export const region=5
export const regionI=1710
export const urlImg="https://kadr.vatanparvar.uz/img/personal/"